packages:
  - "common"
  - "main"
  - "preload"
  - "renderer"

catalog:
  electron: ^36.4.0
  "@types/js-build-tool-types": npm:@iiimaddiniii/js-build-tool-types@1.0.6
  tslib: ^2.8.1
  "@iiimaddiniii/remote-objects": ^0.0.8
  "@lit/localize": ^0.12.2
